version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - storage_data:/var/www/html/storage
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:GtSJDLnHBAfs8dLzOkfvcIfLLZogjD61xPTj6R7TWrM=
      APP_URL: http://localhost:8000

      DB_CONNECTION: mysql
      DB_HOST: 168.231.110.172
      DB_PORT: 4443
      DB_DATABASE: default
      DB_USERNAME: mysql
      DB_PASSWORD: rDDlkNAVzxO5bmpW0J3K9etsKtRvDYHhpaQ8OUa33W6O4bw0xtOL7V9MjjMU4BeJ

      JWT_SECRET: fA67XUAx2di7o06MPiNSg690mj3ETAu8jOeZFFdJeTCEpY9bm8D7Z3ePzUQhm1TI
      JWT_TTL: 1440
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database

volumes:
  storage_data:
